/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface AccountDeletionLogs {
  /**
   * 操作类型
   */
  action: "admin_deleted" | "admin_suspended" | "cancelled" | "completed" | "requested";
  /**
   * 操作时间
   */
  created_at: Generated<Date | null>;
  /**
   * 操作详情
   */
  details: string | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 操作者ID
   */
  operator_id: number | null;
  /**
   * 用户ID
   */
  user_id: number;
}

export interface Achievements {
  /**
   * 成就分类
   */
  category: string | null;
  /**
   * 达成条件类型
   */
  condition_type: string;
  /**
   * 达成条件值
   */
  condition_value: number;
  /**
   * 成就描述
   */
  description: string | null;
  /**
   * 奖励经验值
   */
  exp_reward: Generated<number>;
  /**
   * 图标标识
   */
  icon: string | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 成就名称
   */
  name: string;
  /**
   * 成就标识
   */
  slug: string;
}

export interface AdminOperationLogs {
  /**
   * 操作时间
   */
  created_at: Generated<Date>;
  /**
   * 操作详情
   */
  detail: Json | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 操作类型
   */
  operation: string;
  /**
   * 操作者用户ID
   */
  operator_id: number;
  /**
   * 被操作的用户ID
   */
  target_user_id: number | null;
}

export interface AiGenerations {
  /**
   * 完成时间
   */
  completed_at: Date | null;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 错误信息
   */
  error_message: string | null;
  /**
   * 高度
   */
  height: Generated<number | null>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 入库后的图片ID
   */
  image_id: number | null;
  /**
   * 使用的模型
   */
  model: Generated<string | null>;
  /**
   * 生成提示词
   */
  prompt: string;
  /**
   * 生成结果URL
   */
  result_url: string | null;
  /**
   * 状态
   */
  status: Generated<"completed" | "failed" | "pending" | "processing" | null>;
  /**
   * 风格: realistic/anime/abstract/oil_painting
   */
  style: Generated<string | null>;
  /**
   * 消耗的token数
   */
  tokens_used: Generated<number | null>;
  /**
   * 用户ID
   */
  user_id: number;
  /**
   * 宽度
   */
  width: Generated<number | null>;
}

export interface AiModelProviders {
  /**
   * API密钥
   */
  api_key: string;
  /**
   * API基础URL
   */
  base_url: string;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 是否启用
   */
  enabled: Generated<number>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 提供商名称
   */
  name: string;
  /**
   * 提供商类型
   */
  type: Generated<"anthropic" | "custom" | "google" | "openai">;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
}

export interface AiModels {
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 显示名称
   */
  display_name: string | null;
  /**
   * 是否启用
   */
  enabled: Generated<number>;
  /**
   * 额外配置(如temperature等)
   */
  extra_config: Json | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 是否为该类型默认模型
   */
  is_default: Generated<number>;
  /**
   * 最大token数
   */
  max_tokens: Generated<number | null>;
  /**
   * 模型标识(如gpt-4o)
   */
  model_id: string;
  /**
   * 模型类型
   */
  model_type: Generated<"chat" | "embedding" | "image">;
  /**
   * 提供商ID
   */
  provider_id: number;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
}

export interface ApiKeys {
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 过期时间，NULL表示永不过期
   */
  expires_at: Date | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 是否激活
   */
  is_active: Generated<number>;
  /**
   * SHA256哈希
   */
  key_hash: string;
  /**
   * 前缀用于识别
   */
  key_prefix: string;
  /**
   * 最后使用时间
   */
  last_used_at: Date | null;
  /**
   * Key名称
   */
  name: string;
  /**
   * 每日请求上限
   */
  rate_limit: Generated<number | null>;
  /**
   * API套餐: free/pro/enterprise
   */
  tier: Generated<string | null>;
  /**
   * 所属用户ID
   */
  user_id: number;
}

export interface ApiUsageLogs {
  /**
   * API密钥ID
   */
  api_key_id: number;
  /**
   * 调用时间
   */
  created_at: Generated<Date>;
  /**
   * 调用接口
   */
  endpoint: string;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 请求IP地址
   */
  ip_address: string | null;
  /**
   * 响应状态码
   */
  status_code: number | null;
}

export interface BotConfigs {
  /**
   * App ID（飞书/QQ开放平台应用ID）
   */
  app_id: string | null;
  /**
   * App Secret（飞书/QQ开放平台应用密钥）
   */
  app_secret: string | null;
  /**
   * 认证模式: webhook=Webhook模式, app=App ID模式
   */
  auth_mode: Generated<"app" | "webhook">;
  /**
   * 会话ID（飞书群chat_id/QQ频道channel_id）
   */
  chat_id: string | null;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 自定义请求体模板
   */
  custom_body_template: string | null;
  /**
   * 自定义请求头
   */
  custom_headers: Json | null;
  /**
   * 自定义请求方法
   */
  custom_method: Generated<string | null>;
  /**
   * 默认聊天模型ID
   */
  default_chat_model_id: number | null;
  /**
   * 默认图片生成模型ID
   */
  default_image_model_id: number | null;
  /**
   * 是否启用
   */
  enabled: Generated<number>;
  /**
   * 累计失败次数
   */
  fail_count: Generated<number | null>;
  /**
   * 飞书消息类型
   */
  feishu_msg_type: Generated<string | null>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 最后发送时间
   */
  last_sent_at: Date | null;
  /**
   * 机器人名称
   */
  name: string;
  /**
   * QQ群号
   */
  qq_group_id: string | null;
  /**
   * 签名密钥
   */
  secret: string | null;
  /**
   * 累计发送次数
   */
  send_count: Generated<number | null>;
  /**
   * 订阅的通知事件类型
   */
  subscribe_events: Json | null;
  /**
   * 机器人类型
   */
  type: "custom" | "dingtalk" | "feishu" | "qq" | "slack" | "wechat_work";
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
  /**
   * Webhook 地址
   */
  webhook_url: string;
}

export interface BotMessages {
  /**
   * 关联的机器人配置ID
   */
  bot_config_id: number;
  /**
   * 群聊/频道ID
   */
  chat_id: string | null;
  /**
   * 消息内容
   */
  content: string | null;
  /**
   * 消息时间
   */
  created_at: Generated<Date | null>;
  /**
   * 消息方向: outbound=发送, inbound=接收
   */
  direction: "inbound" | "outbound";
  /**
   * 失败时的错误信息
   */
  error_message: string | null;
  /**
   * 事件类型
   */
  event_type: string | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 消息类型
   */
  message_type: Generated<string | null>;
  /**
   * 平台类型: feishu/qq/dingtalk/wechat_work/slack/custom
   */
  platform: string;
  /**
   * 发送者ID
   */
  sender_id: string | null;
  /**
   * 发送者名称
   */
  sender_name: string | null;
  /**
   * 发送状态
   */
  status: Generated<"failed" | "pending" | "success" | null>;
  /**
   * 消息标题
   */
  title: string | null;
}

export interface Categories {
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 分类名称
   */
  name: string;
  /**
   * 分类标识
   */
  slug: string;
  /**
   * 排序
   */
  sort_order: Generated<number | null>;
}

export interface Challenges {
  /**
   * 活动封面图URL
   */
  banner_url: string | null;
  /**
   * 壁纸分类主题
   */
  category: string | null;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 创建人ID
   */
  created_by: number | null;
  /**
   * 活动描述和规则
   */
  description: string | null;
  /**
   * 结束时间
   */
  end_time: Date;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 每人最大投稿数
   */
  max_submissions: Generated<number | null>;
  /**
   * 奖品描述
   */
  prize_description: string | null;
  /**
   * 奖品经验值
   */
  prize_exp: Generated<number | null>;
  /**
   * 开始时间
   */
  start_time: Date;
  /**
   * 状态
   */
  status: Generated<"active" | "draft" | "ended" | "settled" | null>;
  /**
   * 活动标题
   */
  title: string;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
  /**
   * 每人每天投票数
   */
  votes_per_day: Generated<number | null>;
}

export interface ChallengeSubmissions {
  /**
   * 活动ID
   */
  challenge_id: number;
  /**
   * 投稿时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 投稿图片ID
   */
  image_id: number;
  /**
   * 审核状态
   */
  status: Generated<"approved" | "pending" | "rejected" | null>;
  /**
   * 投稿用户ID
   */
  user_id: number;
}

export interface ChallengeVotes {
  /**
   * 活动ID
   */
  challenge_id: number;
  /**
   * 投票时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 投稿ID
   */
  submission_id: number;
  /**
   * 投票用户ID
   */
  user_id: number;
}

export interface CollectionImages {
  /**
   * 添加时间
   */
  added_at: Generated<Date>;
  /**
   * 图集ID
   */
  collection_id: number;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 图片ID
   */
  image_id: number;
  /**
   * 排序顺序
   */
  sort_order: Generated<number>;
}

export interface Collections {
  /**
   * 封面图片ID
   */
  cover_image_id: number | null;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 图集描述
   */
  description: string | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 是否公开
   */
  is_public: Generated<number>;
  /**
   * 排序顺序
   */
  sort_order: Generated<number>;
  /**
   * 图集标题
   */
  title: string;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
  /**
   * 创建者用户ID
   */
  user_id: number;
}

export interface CollectionSubscriptions {
  /**
   * 图集ID
   */
  collection_id: number;
  /**
   * 订阅时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 订阅用户ID
   */
  user_id: number;
}

export interface Comments {
  /**
   * 评论内容
   */
  content: string;
  /**
   * 评论时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 图片ID（与post_id互斥）
   */
  image_id: number | null;
  /**
   * 点赞数
   */
  like_count: Generated<number | null>;
  /**
   * 父评论ID(用于回复)
   */
  parent_id: number | null;
  /**
   * 帖子ID（与image_id互斥）
   */
  post_id: number | null;
  /**
   * 评论用户ID
   */
  user_id: number;
}

export interface ConversationParticipants {
  /**
   * 对话ID
   */
  conversation_id: number;
  created_at: Generated<Date>;
  id: Generated<number>;
  /**
   * 用户是否隐藏该对话
   */
  is_hidden: Generated<number | null>;
  /**
   * 最后已读消息时间
   */
  last_read_at: Date | null;
  /**
   * 用户ID
   */
  user_id: number;
}

export interface Conversations {
  /**
   * 对话创建时间
   */
  created_at: Generated<Date>;
  id: Generated<number>;
  /**
   * 最后更新时间(最后消息时间)
   */
  updated_at: Generated<Date>;
}

export interface CrawlLogs {
  /**
   * 指定的分类
   */
  category: string | null;
  /**
   * 爬取模式
   */
  crawl_mode: Generated<string | null>;
  /**
   * 去重跳过数量
   */
  dedup_skipped: Generated<number | null>;
  /**
   * 耗时秒
   */
  duration_seconds: number | null;
  /**
   * 错误信息
   */
  error_message: string | null;
  /**
   * 失败数量
   */
  fail_count: Generated<number | null>;
  /**
   * 完成时间
   */
  finished_at: Date | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 操作人用户ID
   */
  operator_id: number | null;
  /**
   * 爬取页数
   */
  pages: Generated<number | null>;
  /**
   * 请求爬取数量
   */
  requested_count: Generated<number | null>;
  /**
   * 爬取源标识
   */
  source: string;
  /**
   * 爬取的目标URL
   */
  source_url: string | null;
  /**
   * 开始时间
   */
  started_at: Generated<Date | null>;
  /**
   * 任务状态
   */
  status: Generated<string | null>;
  /**
   * 成功数量
   */
  success_count: Generated<number | null>;
  /**
   * 指定的标签，逗号分隔
   */
  tags: string | null;
}

export interface CrawlPreviewItems {
  /**
   * 分类
   */
  category: string | null;
  created_at: Generated<Date | null>;
  /**
   * 文件大小(字节)
   */
  file_size: Generated<number | null>;
  /**
   * 高度
   */
  height: Generated<number | null>;
  id: Generated<number>;
  /**
   * 是否被用户选中
   */
  is_selected: Generated<number | null>;
  /**
   * 媒体类型
   */
  media_type: Generated<"image" | "video" | null>;
  /**
   * MIME类型
   */
  mime_type: string | null;
  /**
   * 封面图URL
   */
  poster_url: string | null;
  /**
   * 关联 crawl_sessions.id
   */
  session_id: number;
  /**
   * 爬取来源
   */
  source: string | null;
  /**
   * 原始图片/视频URL
   */
  source_url: string | null;
  /**
   * 标签
   */
  tags: string | null;
  /**
   * 图片标题
   */
  title: string | null;
  /**
   * 视频原始URL
   */
  video_url: string | null;
  /**
   * 宽度
   */
  width: Generated<number | null>;
}

export interface CrawlSessions {
  /**
   * 分类
   */
  category: string | null;
  /**
   * 关联 crawl_logs 表
   */
  crawl_log_id: number | null;
  created_at: Generated<Date | null>;
  id: Generated<number>;
  /**
   * 成功入库的数量
   */
  imported_count: Generated<number | null>;
  /**
   * 用户选中的数量
   */
  selected_count: Generated<number | null>;
  /**
   * 固定源名称
   */
  source_type: string | null;
  /**
   * 爬取来源URL
   */
  source_url: string | null;
  /**
   * 会话状态
   */
  status: Generated<"completed" | "discarded" | "importing" | "pending" | null>;
  /**
   * 标签
   */
  tags: string | null;
  /**
   * 爬取到的图片总数
   */
  total_count: Generated<number | null>;
  updated_at: Generated<Date | null>;
}

export interface CrawlSources {
  created_at: Generated<Date>;
  /**
   * 描述
   */
  description: Generated<string | null>;
  id: Generated<number>;
  /**
   * 源名称
   */
  name: string;
  updated_at: Generated<Date>;
  /**
   * 源URL
   */
  url: string;
}

export interface DownloadLogs {
  /**
   * 下载时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 图片ID
   */
  image_id: number;
  /**
   * 请求IP地址
   */
  ip_address: string | null;
  /**
   * 下载分辨率
   */
  resolution: string | null;
  /**
   * 下载用户ID
   */
  user_id: number | null;
}

export interface Earnings {
  /**
   * 收益金额
   */
  amount: Decimal;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 净收益
   */
  net_amount: Decimal;
  /**
   * 平台抽成
   */
  platform_fee: Generated<Decimal | null>;
  /**
   * 关联ID(订单ID/打赏ID)
   */
  related_id: number | null;
  /**
   * 状态
   */
  status: Generated<"available" | "pending" | "withdrawn" | null>;
  /**
   * 收益类型
   */
  type: "membership_share" | "paid_download" | "tip";
  /**
   * 创作者ID
   */
  user_id: number;
}

export interface EmailCampaignLogs {
  /**
   * 营销活动ID
   */
  campaign_id: number;
  /**
   * 点击时间
   */
  clicked_at: Date | null;
  created_at: Generated<Date>;
  /**
   * 邮箱地址
   */
  email: string;
  /**
   * 失败原因
   */
  error_message: string | null;
  id: Generated<number>;
  /**
   * 打开时间
   */
  opened_at: Date | null;
  /**
   * 发送状态
   */
  status: Generated<"bounced" | "clicked" | "failed" | "opened" | "sent">;
  /**
   * 用户ID
   */
  user_id: number;
}

export interface EmailCampaigns {
  /**
   * 邮件HTML内容
   */
  body_html: string;
  /**
   * 邮件纯文本内容
   */
  body_text: string | null;
  /**
   * 营销类型
   */
  campaign_type: Generated<"activity_notice" | "creator_update" | "system" | "weekly_digest">;
  /**
   * 点击人数
   */
  click_count: Generated<number | null>;
  created_at: Generated<Date>;
  /**
   * 创建人ID
   */
  created_by: number | null;
  id: Generated<number>;
  /**
   * 打开人数
   */
  open_count: Generated<number | null>;
  /**
   * 计划发送时间
   */
  scheduled_at: Date | null;
  /**
   * 实际发送时间
   */
  sent_at: Date | null;
  /**
   * 已发送人数
   */
  sent_count: Generated<number | null>;
  /**
   * 状态
   */
  status: Generated<"completed" | "draft" | "failed" | "scheduled" | "sending">;
  /**
   * 邮件主题
   */
  subject: string;
  /**
   * 目标接收人数
   */
  target_count: Generated<number | null>;
  /**
   * 关联邮件模板key
   */
  template_key: string | null;
  updated_at: Generated<Date>;
}

export interface EmailSubscriptions {
  /**
   * 接收活动通知
   */
  activity_notice: Generated<number | null>;
  created_at: Generated<Date>;
  /**
   * 接收创作者动态
   */
  creator_update: Generated<number | null>;
  /**
   * 邮箱地址
   */
  email: string;
  id: Generated<number>;
  /**
   * 是否全局退订
   */
  is_unsubscribed: Generated<number | null>;
  /**
   * 退订token
   */
  unsub_token: string;
  /**
   * 退订时间
   */
  unsubscribed_at: Date | null;
  updated_at: Generated<Date>;
  /**
   * 用户ID
   */
  user_id: number;
  /**
   * 接收每周精选
   */
  weekly_digest: Generated<number | null>;
}

export interface EmailTemplates {
  /**
   * HTML邮件正文(支持变量)
   */
  body_html: string;
  /**
   * 纯文本邮件正文(支持变量)
   */
  body_text: string | null;
  /**
   * 模板分类
   */
  category: Generated<"auth" | "notification" | "review" | "social" | "system" | null>;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 模板描述
   */
  description: string | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 是否启用
   */
  is_active: Generated<number | null>;
  /**
   * 是否系统内置模板(不可删除)
   */
  is_builtin: Generated<number | null>;
  /**
   * 模板名称
   */
  name: string;
  /**
   * 邮件主题(支持变量)
   */
  subject: string;
  /**
   * 模板唯一标识(如 welcome, password_reset, review_result)
   */
  template_key: string;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
  /**
   * 模板可用变量定义 [{key, label, example}]
   */
  variables: Json | null;
}

export interface EmbedStats {
  /**
   * 记录时间
   */
  created_at: Generated<Date>;
  /**
   * 嵌入类型
   */
  embed_type: "daily" | "wallpaper";
  /**
   * 事件类型
   */
  event_type: Generated<"click" | "impression" | null>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 图片ID
   */
  image_id: number | null;
  /**
   * 来源URL
   */
  referrer: string | null;
}

export interface Favorites {
  /**
   * 收藏时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 收藏图片ID
   */
  image_id: number;
  /**
   * 收藏用户ID
   */
  user_id: number;
}

export interface Feedback {
  /**
   * 反馈分类
   */
  category: Generated<"bug" | "feature" | "improvement" | "other" | null>;
  /**
   * 反馈内容
   */
  content: string;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 反馈页面URL
   */
  page_url: string | null;
  /**
   * 处理备注
   */
  resolution_note: string | null;
  /**
   * 处理人ID
   */
  resolved_by: number | null;
  /**
   * 截图URL
   */
  screenshot_url: string | null;
  /**
   * 处理状态
   */
  status: Generated<"closed" | "in_progress" | "pending" | "resolved" | null>;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
  /**
   * 用户浏览器标识
   */
  user_agent: string | null;
  /**
   * 反馈用户ID
   */
  user_id: number | null;
}

export interface Images {
  /**
   * 作者
   */
  author: Generated<string | null>;
  /**
   * 分类
   */
  category: Generated<string | null>;
  /**
   * 调色板JSON数组
   */
  color_palette: string | null;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 图片描述
   */
  description: string | null;
  /**
   * 主色调HEX值
   */
  dominant_color: string | null;
  /**
   * 下载次数
   */
  download_count: Generated<number>;
  /**
   * EXIF 元数据 JSON
   */
  exif: Json | null;
  /**
   * 收藏数
   */
  favorite_count: Generated<number | null>;
  /**
   * 文件大小(字节)
   */
  file_size: Generated<number | null>;
  /**
   * 原始文件名
   */
  filename: string;
  /**
   * 图片高度
   */
  height: Generated<number | null>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 是否收藏
   */
  is_favorite: Generated<number | null>;
  /**
   * 媒体类型: image/video(动态壁纸)
   */
  media_type: Generated<string | null>;
  /**
   * 文件类型
   */
  mime_type: Generated<string | null>;
  /**
   * 是否被NSFW检测标记为可疑
   */
  nsfw_flagged: Generated<number | null>;
  /**
   * NSFW检测各分类概率
   */
  nsfw_score: Json | null;
  /**
   * 感知哈希值(用于去重)
   */
  phash: string | null;
  /**
   * 视频封面图URL
   */
  poster_url: string | null;
  /**
   * 拒绝原因
   */
  reject_reason: string | null;
  /**
   * 审核时间
   */
  reviewed_at: Date | null;
  /**
   * 审核人ID
   */
  reviewed_by: number | null;
  /**
   * 来源:upload/ai_generated/crawled
   */
  source_type: Generated<string | null>;
  /**
   * 审核状态: pending/approved/rejected
   */
  status: Generated<string | null>;
  /**
   * 对象存储路径
   */
  storage_key: string;
  /**
   * 标签(逗号分隔)
   */
  tags: Generated<string | null>;
  /**
   * 缩略图URL
   */
  thumbnail_url: string | null;
  /**
   * 预生成的缩略图信息
   */
  thumbnails: Json | null;
  /**
   * 图片标题
   */
  title: Generated<string>;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
  /**
   * 上传者ID
   */
  uploaded_by: number | null;
  /**
   * 公开访问URL
   */
  url: string;
  /**
   * 预生成的变体信息
   */
  variants: Json | null;
  /**
   * 动态壁纸视频URL
   */
  video_url: string | null;
  /**
   * 浏览次数
   */
  view_count: Generated<number | null>;
  /**
   * 图片宽度
   */
  width: Generated<number | null>;
}

export interface ImageTags {
  /**
   * 图片ID
   */
  image_id: number;
  /**
   * 标签ID
   */
  tag_id: number;
}

export interface MembershipRedeemCodes {
  /**
   * 批次名称
   */
  batch_name: string | null;
  /**
   * 兑换码
   */
  code: string;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 创建者管理员ID
   */
  created_by: number;
  /**
   * 有效天数
   */
  duration_days: number;
  /**
   * 兑换码本身的过期时间
   */
  expires_at: Date | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 最大兑换次数
   */
  max_uses: Generated<number>;
  /**
   * 备注说明
   */
  note: string | null;
  /**
   * 对应的会员套餐
   */
  plan: "monthly" | "yearly";
  /**
   * 状态
   */
  status: Generated<"active" | "disabled" | "expired" | null>;
  /**
   * 已兑换次数
   */
  used_count: Generated<number>;
}

export interface MembershipRedeemLogs {
  /**
   * 兑换码
   */
  code: string;
  /**
   * 兑换码ID
   */
  code_id: number;
  /**
   * 获得的天数
   */
  duration_days: number;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 关联的会员记录ID
   */
  membership_id: number | null;
  /**
   * 兑换的套餐
   */
  plan: "monthly" | "yearly";
  /**
   * 兑换时间
   */
  redeemed_at: Generated<Date>;
  /**
   * 兑换用户ID
   */
  user_id: number;
}

export interface Memberships {
  /**
   * 自动续费
   */
  auto_renew: Generated<number | null>;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 到期时间
   */
  expires_at: Date | null;
  /**
   * 发放者管理员ID
   */
  granted_by: number | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 套餐类型
   */
  plan: Generated<"free" | "monthly" | "yearly" | null>;
  /**
   * 兑换码ID
   */
  redeem_code_id: number | null;
  /**
   * 会员来源
   */
  source: Generated<"admin_grant" | "payment" | "redeem_code">;
  /**
   * 开始时间
   */
  started_at: Date | null;
  /**
   * 状态
   */
  status: Generated<"active" | "cancelled" | "expired" | null>;
  /**
   * 用户ID
   */
  user_id: number;
}

export interface Messages {
  /**
   * 消息内容
   */
  content: string;
  /**
   * 对话ID
   */
  conversation_id: number;
  /**
   * 消息发送时间
   */
  created_at: Generated<Date>;
  id: Generated<number>;
  /**
   * 接收者是否已读
   */
  is_read: Generated<number | null>;
  /**
   * 消息类型
   */
  message_type: Generated<"image" | "system" | "text" | null>;
  /**
   * 发送者ID
   */
  sender_id: number;
}

export interface Notifications {
  /**
   * 通知内容
   */
  content: string | null;
  /**
   * 通知时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 是否已读
   */
  is_read: Generated<number | null>;
  /**
   * 关联资源ID(如图片ID)
   */
  related_id: number | null;
  /**
   * 关联资源类型
   */
  related_type: "achievement" | "collection" | "image" | "report" | "user" | null;
  /**
   * 通知标题
   */
  title: string;
  /**
   * 通知类型
   */
  type: "achievement" | "comment" | "favorite" | "follow" | "like" | "message" | "order" | "review" | "system";
  /**
   * 接收通知的用户
   */
  user_id: number;
}

export interface NotificationSettings {
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 成就解锁邮件
   */
  email_achievement: Generated<number | null>;
  /**
   * 私信通知邮件
   */
  email_message: Generated<number | null>;
  /**
   * 审核结果邮件
   */
  email_review: Generated<number | null>;
  /**
   * 系统通知邮件
   */
  email_system: Generated<number | null>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 成就解锁通知
   */
  notify_achievement: Generated<number | null>;
  /**
   * 评论通知
   */
  notify_comment: Generated<number | null>;
  /**
   * 收藏通知
   */
  notify_favorite: Generated<number | null>;
  /**
   * 关注通知
   */
  notify_follow: Generated<number | null>;
  /**
   * 点赞通知
   */
  notify_like: Generated<number | null>;
  /**
   * 私信通知
   */
  notify_message: Generated<number | null>;
  /**
   * 审核结果通知
   */
  notify_review: Generated<number | null>;
  /**
   * 系统通知
   */
  notify_system: Generated<number | null>;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
  /**
   * 用户ID
   */
  user_id: number;
}

export interface OauthAccounts {
  /**
   * 访问令牌
   */
  access_token: string | null;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * OAuth提供商(github/google等)
   */
  provider: string;
  /**
   * 第三方账号ID
   */
  provider_account_id: string;
  /**
   * 刷新令牌
   */
  refresh_token: string | null;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
  /**
   * 用户ID
   */
  user_id: number;
}

export interface Orders {
  /**
   * 订单金额
   */
  amount: Decimal;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 支付时间
   */
  paid_at: Date | null;
  /**
   * 第三方支付ID
   */
  payment_id: string | null;
  /**
   * 支付方式
   */
  payment_method: "alipay" | "wechat" | null;
  /**
   * 支付状态
   */
  payment_status: Generated<"failed" | "paid" | "pending" | "refunded" | null>;
  /**
   * 关联ID
   */
  related_id: number | null;
  /**
   * 订单类型
   */
  type: "membership" | "paid_wallpaper" | "tip";
  /**
   * 购买者ID
   */
  user_id: number;
}

export interface PaidWallpapers {
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 免费预览图URL
   */
  free_preview_url: string | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 图片ID
   */
  image_id: number;
  /**
   * 是否为付费壁纸
   */
  is_paid: Generated<number | null>;
  /**
   * 价格(元)
   */
  price: Generated<Decimal>;
  /**
   * 创作者ID
   */
  user_id: number;
}

export interface PasswordResetTokens {
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 过期时间
   */
  expires_at: Date;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 重置令牌
   */
  token: string;
  /**
   * 使用时间
   */
  used_at: Date | null;
  /**
   * 用户ID
   */
  user_id: number;
}

export interface PostAttachments {
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 高度
   */
  height: Generated<number | null>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 关联帖子ID
   */
  post_id: number;
  /**
   * 排序
   */
  sort_order: Generated<number | null>;
  /**
   * 缩略图URL
   */
  thumbnail_url: string | null;
  /**
   * 附件类型
   */
  type: "image" | "video";
  /**
   * 附件URL
   */
  url: string;
  /**
   * 宽度
   */
  width: Generated<number | null>;
}

export interface PostLikes {
  /**
   * 点赞时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 帖子ID
   */
  post_id: number;
  /**
   * 点赞用户ID
   */
  user_id: number;
}

export interface PostLinkPreviews {
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 链接描述
   */
  description: string | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 链接预览图
   */
  image_url: string | null;
  /**
   * 关联帖子ID
   */
  post_id: number;
  /**
   * 站点名称
   */
  site_name: string | null;
  /**
   * 链接标题
   */
  title: string | null;
  /**
   * 链接URL
   */
  url: string;
}

export interface Posts {
  /**
   * 附件数量
   */
  attachments_count: Generated<number | null>;
  /**
   * 评论数
   */
  comments_count: Generated<number | null>;
  /**
   * 帖子内容
   */
  content: string;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 是否置顶
   */
  is_pinned: Generated<number | null>;
  /**
   * 点赞数
   */
  likes_count: Generated<number | null>;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
  /**
   * 发布用户ID
   */
  user_id: number;
  /**
   * 可见范围
   */
  visibility: Generated<"followers" | "private" | "public" | null>;
}

export interface Reports {
  /**
   * 举报时间
   */
  created_at: Generated<Date | null>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 被举报的图片ID
   */
  image_id: number;
  /**
   * 举报原因
   */
  reason: string;
  /**
   * 举报人ID
   */
  reporter_id: number;
  /**
   * 处理时间
   */
  resolved_at: Date | null;
  /**
   * 处理人ID
   */
  resolved_by: number | null;
  /**
   * 举报状态: pending/reviewed/resolved
   */
  status: Generated<string | null>;
}

export interface SysAnnouncements {
  /**
   * 发布人ID
   */
  author_id: number | null;
  /**
   * 公告内容
   */
  content: string;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 生效结束时间
   */
  end_time: Date | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 是否发布
   */
  is_published: Generated<number | null>;
  /**
   * 优先级
   */
  priority: Generated<"high" | "low" | "normal" | "urgent" | null>;
  /**
   * 生效开始时间
   */
  start_time: Date | null;
  /**
   * 公告标题
   */
  title: string;
  /**
   * 类型
   */
  type: Generated<"announcement" | "maintenance" | "notice" | null>;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
}

export interface SysMenus {
  /**
   * 组件路径
   */
  component: Generated<string | null>;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 菜单图标
   */
  icon: Generated<string | null>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 是否启用
   */
  is_enabled: Generated<number | null>;
  /**
   * 是否可见
   */
  is_visible: Generated<number | null>;
  /**
   * 菜单名称
   */
  name: string;
  /**
   * 父菜单ID，0为顶级菜单
   */
  parent_id: Generated<number | null>;
  /**
   * 路由路径
   */
  path: Generated<string | null>;
  /**
   * 权限标识
   */
  permission: Generated<string | null>;
  /**
   * 排序顺序
   */
  sort_order: Generated<number | null>;
  /**
   * 菜单类型
   */
  type: Generated<"button" | "directory" | "menu" | null>;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
}

export interface SysRoleMenus {
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 菜单ID
   */
  menu_id: number;
  /**
   * 角色ID
   */
  role_id: number;
}

export interface SysRoles {
  /**
   * 角色编码
   */
  code: string;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 角色描述
   */
  description: Generated<string | null>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 是否启用
   */
  is_enabled: Generated<number | null>;
  /**
   * 角色名称
   */
  name: string;
  /**
   * 排序
   */
  sort_order: Generated<number | null>;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
}

export interface SystemSettings {
  /**
   * 配置说明
   */
  description: string | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 配置键
   */
  setting_key: string;
  /**
   * 配置值
   */
  setting_value: string | null;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
}

export interface Tags {
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 关联图片数
   */
  image_count: Generated<number>;
  /**
   * 标签名称
   */
  name: string;
  /**
   * 标签标识
   */
  slug: string;
}

export interface ThemeZoneImages {
  added_at: Generated<Date | null>;
  id: Generated<number>;
  image_id: number;
  sort_order: Generated<number | null>;
  zone_key: string;
}

export interface Tips {
  /**
   * 打赏金额(元)
   */
  amount: Decimal;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 打赏人ID
   */
  from_user_id: number;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 关联图片ID
   */
  image_id: number | null;
  /**
   * 打赏留言
   */
  message: string | null;
  /**
   * 支付方式
   */
  payment_method: string | null;
  /**
   * 状态
   */
  status: Generated<"completed" | "pending" | "refunded" | null>;
  /**
   * 被打赏人ID
   */
  to_user_id: number;
}

export interface UserAchievements {
  /**
   * 成就ID
   */
  achievement_id: number;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 解锁时间
   */
  unlocked_at: Generated<Date>;
  /**
   * 用户ID
   */
  user_id: number;
}

export interface UserFollows {
  /**
   * 关注时间
   */
  created_at: Generated<Date>;
  /**
   * 关注者ID
   */
  follower_id: number;
  /**
   * 被关注者ID
   */
  following_id: number;
  /**
   * ID
   */
  id: Generated<number>;
}

export interface UserLevels {
  /**
   * 徽章列表
   */
  badges: Json | null;
  /**
   * 经验值
   */
  exp: Generated<number>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 等级
   */
  level: Generated<number>;
  /**
   * 等级称号
   */
  title: string | null;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
  /**
   * 用户ID
   */
  user_id: number;
}

export interface Users {
  /**
   * 头像URL
   */
  avatar: string | null;
  /**
   * 封禁时间
   */
  banned_at: Date | null;
  /**
   * 封禁原因
   */
  banned_reason: string | null;
  /**
   * 主页Banner图URL
   */
  banner: string | null;
  /**
   * 个人简介
   */
  bio: string | null;
  /**
   * 品牌描述
   */
  brand_description: string | null;
  /**
   * 品牌名
   */
  brand_name: string | null;
  /**
   * 品牌官网
   */
  brand_website: string | null;
  /**
   * 注册时间
   */
  created_at: Generated<Date>;
  /**
   * 注销请求时间
   */
  deletion_requested_at: Date | null;
  /**
   * 计划删除时间
   */
  deletion_scheduled_at: Date | null;
  /**
   * 邮箱
   */
  email: string;
  /**
   * 精选合集ID列表(置顶)
   */
  featured_collections: Json | null;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 是否认证创作者
   */
  is_verified: Generated<number | null>;
  /**
   * 昵称
   */
  name: Generated<string>;
  /**
   * 密码哈希
   */
  password: string;
  /**
   * 角色
   */
  role: Generated<"admin" | "creator" | "moderator" | "user">;
  /**
   * 社交链接（微博/推特/B站/小红书等）
   */
  social_links: Json | null;
  /**
   * 账号状态
   */
  status: Generated<"active" | "banned" | "deleted" | "pending_deletion" | "suspended" | null>;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
  /**
   * 认证申请时间
   */
  verification_applied_at: Date | null;
  /**
   * 身份证明编号
   */
  verification_id_number: string | null;
  /**
   * 身份证明类型
   */
  verification_id_type: string | null;
  /**
   * 作品集链接
   */
  verification_portfolio_url: string | null;
  /**
   * 申请人真实姓名
   */
  verification_real_name: string | null;
  /**
   * 认证拒绝原因
   */
  verification_rejected_reason: string | null;
  /**
   * 认证状态
   */
  verification_status: Generated<"approved" | "none" | "pending" | "rejected" | null>;
  /**
   * 认证时间
   */
  verified_at: Date | null;
}

export interface ViewLogs {
  /**
   * 浏览时间
   */
  created_at: Generated<Date>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 图片ID
   */
  image_id: number;
  /**
   * 请求IP地址
   */
  ip_address: string | null;
  /**
   * 浏览用户ID
   */
  user_id: number | null;
}

export interface WebhookDeliveryLogs {
  /**
   * 第几次尝试
   */
  attempt: Generated<number | null>;
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 投递时间
   */
  delivered_at: Date | null;
  /**
   * 事件类型
   */
  event: string;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 请求体
   */
  payload: Json;
  /**
   * 响应内容
   */
  response_body: string | null;
  /**
   * HTTP响应状态码
   */
  response_status: number | null;
  /**
   * 订阅ID
   */
  subscription_id: number;
  /**
   * 是否成功
   */
  success: Generated<number | null>;
}

export interface WebhookSubscriptions {
  /**
   * 创建时间
   */
  created_at: Generated<Date>;
  /**
   * 累计投递次数
   */
  delivery_count: Generated<number | null>;
  /**
   * 是否启用
   */
  enabled: Generated<number>;
  /**
   * 订阅的事件列表
   */
  events: Json;
  /**
   * 累计失败次数
   */
  fail_count: Generated<number | null>;
  /**
   * ID
   */
  id: Generated<number>;
  /**
   * 最后成功投递时间
   */
  last_delivered_at: Date | null;
  /**
   * 最大重试次数
   */
  max_retries: Generated<number | null>;
  /**
   * 重试间隔(秒)
   */
  retry_interval: Generated<number | null>;
  /**
   * 签名密钥
   */
  secret: string | null;
  /**
   * 请求超时(毫秒)
   */
  timeout_ms: Generated<number | null>;
  /**
   * 更新时间
   */
  updated_at: Generated<Date>;
  /**
   * Webhook回调地址
   */
  url: string;
  /**
   * 订阅用户ID
   */
  user_id: number;
}

export interface DB {
  account_deletion_logs: AccountDeletionLogs;
  achievements: Achievements;
  admin_operation_logs: AdminOperationLogs;
  ai_generations: AiGenerations;
  ai_model_providers: AiModelProviders;
  ai_models: AiModels;
  api_keys: ApiKeys;
  api_usage_logs: ApiUsageLogs;
  bot_configs: BotConfigs;
  bot_messages: BotMessages;
  categories: Categories;
  challenge_submissions: ChallengeSubmissions;
  challenge_votes: ChallengeVotes;
  challenges: Challenges;
  collection_images: CollectionImages;
  collection_subscriptions: CollectionSubscriptions;
  collections: Collections;
  comments: Comments;
  conversation_participants: ConversationParticipants;
  conversations: Conversations;
  crawl_logs: CrawlLogs;
  crawl_preview_items: CrawlPreviewItems;
  crawl_sessions: CrawlSessions;
  crawl_sources: CrawlSources;
  download_logs: DownloadLogs;
  earnings: Earnings;
  email_campaign_logs: EmailCampaignLogs;
  email_campaigns: EmailCampaigns;
  email_subscriptions: EmailSubscriptions;
  email_templates: EmailTemplates;
  embed_stats: EmbedStats;
  favorites: Favorites;
  feedback: Feedback;
  image_tags: ImageTags;
  images: Images;
  membership_redeem_codes: MembershipRedeemCodes;
  membership_redeem_logs: MembershipRedeemLogs;
  memberships: Memberships;
  messages: Messages;
  notification_settings: NotificationSettings;
  notifications: Notifications;
  oauth_accounts: OauthAccounts;
  orders: Orders;
  paid_wallpapers: PaidWallpapers;
  password_reset_tokens: PasswordResetTokens;
  post_attachments: PostAttachments;
  post_likes: PostLikes;
  post_link_previews: PostLinkPreviews;
  posts: Posts;
  reports: Reports;
  sys_announcements: SysAnnouncements;
  sys_menus: SysMenus;
  sys_role_menus: SysRoleMenus;
  sys_roles: SysRoles;
  system_settings: SystemSettings;
  tags: Tags;
  theme_zone_images: ThemeZoneImages;
  tips: Tips;
  user_achievements: UserAchievements;
  user_follows: UserFollows;
  user_levels: UserLevels;
  users: Users;
  view_logs: ViewLogs;
  webhook_delivery_logs: WebhookDeliveryLogs;
  webhook_subscriptions: WebhookSubscriptions;
}
